/* This file is automatically generated. Edits will be lost.*/
<<<<<<< HEAD
const int buildversion = 26;
=======
const int buildversion = 6;
>>>>>>> bc66a3fce7cd8efadf111ffbb0bc7d63613f90e4
const char buildconfig[] = "ASST2";
